[package]
name = "rust-actix-labx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0" # actor framework
actix-rt = "2.7.0"
time = "0.3.13"
